### ISSUE TITLE
Solutions Key and bookdown repository

### ISSUE THREAD

**Issue by hathawayj** [robjhyndman/fpp2#1]
Rob,

   It looks like the book is publically available but I don't see a GitHub repository for the book source.  Is that by design or am I just not searching in the right place?

   I noticed on your blog post that you provide the answer key to faculty.  However, I didn't catch the request mechanism.  

Thanks,

J.

**Comment by robjhyndman** [comment]
For now, the source is private, but the html output is public. We may make it all public at some stage.

The solutions to exercises are largely incomplete. But what we have is available at https://github.com/robjhyndman/fppsolutions. Feel free to fix any solutions, add missing ones, etc.
