### ISSUE TITLE
Request to convert .rda to .csv for non-R users

### ISSUE THREAD

**Issue by dsnair** [robjhyndman/fpp2#3]
Hello, I am currently reading your FPP book and I am a Python user. I was wondering if you could convert the .rda data files to .csv so that I could run Python equivalency of the analyses? Thanks!

**Comment by robjhyndman** [comment]
Use write.csv()

**Comment by dsnair** [comment]
As I mentioned earlier, I am NOT an R user! I understand my request is of inconvenience to you. Perhaps, I should look for other books with wider support for other languages. Thank you for taking the time to respond!

**Comment by claudefalbriard** [comment]
Good question, any hints how to convert .rda files into a standard .csv format?

**Comment by robjhyndman** [comment]
Did you try the answer already provided?

**Comment by claudefalbriard** [comment]
As Ms. DsNair stated, we usually are user with a non-R profile, like a Python coder and we want to access R data repositories in a .rda binary format. Watching for a python utility class able to load the .rda data. Just in imagination, in pandas to have a load.rda() function.
