### ISSUE TITLE
how did you host and publish the fpp2 online book?

### ISSUE THREAD

**Issue by knail1** [robjhyndman/fpp2#4]
I really enjoyed reading your online book here:

https://otexts.org/fpp2/

was trying to figure out how you published this book (meaning, what tool did you use, where is the git repo if its public for the book etc?)

I want to publish similar text using your model, and wanted to learn how you did it

example:
the source for http://trunkbaseddevelopment.com/ is at
https://github.com/paul-hammant/tbd
which walks through how to install and use the tools (hugo etc) to run it locally etc.

I know this is not an issue, but i was trying to reach out to you somehow :)

thank you!
Omer

**Comment by robjhyndman** [comment]
The book is produced using bookdown (see bookdown.org). We've chosen not to make our source files available, but many other bookdown books are on github. See https://bookdown.org/yihui/bookdown/ for details.
