### ISSUE TITLE
data set 'visnights' missing?

### ISSUE THREAD

**Issue by samuel-bohman** [robjhyndman/fpp2#5]
Cannot find the 'visnights' data set in the package, which is referred to in the book. Has this data set been replaced by the data set 'vn'?

**Comment by robjhyndman** [comment]
Use the fpp2 package, not the fpp package.

**Comment by samuel-bohman** [comment]
I did use fpp2 package, but it was an older version. I downloaded the development version and 'visnights' showed up as expected.
