### ISSUE TITLE
ARIMA forecasting at the textbook

### ISSUE THREAD

**Issue by htcml** [robjhyndman/fpp2#6]
I am reading FPP2. I don't know where I can post a question, so I post here to see if I can get an answer from Rob. In Chapter 8 ARIMA models, almost all the forecasts for future time are just flat trend lines. I wonder if this is the case, what is the use of ARIMA models? Examples: Figure 8.8 @ p.237, Figure 8.15 @ p.247, Figure 8.27 @ p.264.

**Comment by robjhyndman** [comment]
Keep reading.
