### ISSUE TITLE
An issue with tslm and lambda

### ISSUE THREAD

**Issue by Apratimguha** [robjhyndman/fpp2#8]
I was using the following piece of code to use tslm function on the inbuilt dataset "elecdaily":

model1 = tslm(Demand~trend+I(trend^2)+season, lambda = "auto", data = elecdaily)

which gives me the following error:
Warning message:
In guerrero(x, lower, upper) :
  Guerrero's method for selecting a Box-Cox parameter (lambda) is given for strictly positive data.

However, the Demand variable in elecdaily is all positive.

Moreover, this produced a lambda value around 0.3, while BoxCox.lambda(elecdaily[,"Demand"]) produced -0.9999242.

The forecasts are also coming all wrong. 

What could be the reason, and what is a way around?

**Comment by robjhyndman** [comment]
Looks like a bug in the `forecast` package. In any case, automatic selection of the Box-Cox parameter is unreliable. The following works:
```r
library(fpp2)
model1 <- tslm(Demand ~ trend + I(trend^2) + season, lambda = 0.3, data = elecdaily)
forecast(model1) %>% autoplot()
```

**Comment by Apratimguha** [comment]
Thanks a lot for your reply. But I am getting this:
BoxCox.lambda(elecdaily[,"Demand"])
[1] -0.9999242

So I am taking lambda to be -1. And then, when I write 
model1 <- tslm(Demand ~ trend + I(trend^2) + season, lambda = -1, data = elecdaily)
I am getting an error.

Incidentally, the following is working. 
Demand = elecdaily[,"Demand"]
model1 <- tslm(Demand ~ trend + I(trend^2) + season, lambda ="auto")
forecast(model1) %>% autopilot()

The problem happens whenever I am calling the dataset directly.

**Comment by robjhyndman** [comment]
So don't use lambda=-1. As I said, the automatic selection is unreliable.

**Comment by mitchelloharawild** [comment]
Fixed in https://github.com/robjhyndman/forecast/commit/43449278f3f79cfc702ba577b2c7c7c92a2c7799

**Comment by Apratimguha** [comment]
@robjhyndman lambda = -1 is not the issue. It is producing decent stable forecasts when the "data=" call is removed.

@mitchelloharawild Can I update that package? Or do I download from Github?

**Comment by robjhyndman** [comment]
You can install the github version of the package using

```r
install.packages("remotes")
remotes::install_github('robjhyndman/forecast')
```
